# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-10 17:16
from __future__ import unicode_literals

import Log.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=32, unique=True)),
                ('ip', models.CharField(max_length=20, validators=[Log.models.IPValidator])),
                ('port', models.PositiveIntegerField(validators=[Log.models.PortValidator])),
                ('submission_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
