# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 08:55
from __future__ import unicode_literals

import Log.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='filename',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='log',
            name='ip',
            field=models.CharField(max_length=15, validators=[Log.models.IPValidator]),
        ),
    ]
