# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-14 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0002_auto_20180814_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='filename',
            field=models.CharField(max_length=64),
        ),
    ]
